include:
  - local: .gitlab/ci/workflows/matrix_deploy.yml

stages:
  - .pre
  - deploy

run:
  extends:
    - .gitlab/ci/workflows/matrix_deploy.yml
  stage: deploy
  trigger:
    include:
      - local: .gitlab/ci/pipeline/environment.yml
    strategy: depend
  needs: []
  rules:
    - when: manual