include:
  - local: .gitlab/ci/workflows/matrix_deploy.yml

stages:
  - .pre
  - deploy

run:
  extends:
    - .matrix_deploy_provider
  stage: deploy
  trigger:
    include:
      - local: .gitlab/ci/pipeline/environment.yml
    strategy: depend
  tags:
    - gitlab-org-docker
  needs: []
  rules:
    - when: manual