include:
  - local: .gitlab/ci/workflows/matrix_deploy.yml

stages:
  - .pre
  - deploy

run:
  extends:
    - .matrix_deploy_provider
  stage: deploy
  trigger:
    include:
      - local: .gitlab/ci/pipeline/environment.yml
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true
  needs: []
